[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x84_64-rust_os.json"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[target.'cfg(target_os = "x84_64-rust_os.json")']
runner = "qemu-system-x86_64 -drive format=raw,file=target/x84_64-rust_os/debug/bootimage-rust_os.bin -serial stdio"
rustflags = ["-C", "link-args=-Tlinker.ld"]