[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x84_64-rust_os.json"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"